### ISSUE TITLE
kernel dies iruby notebook

### ISSUE THREAD

**Issue by AbhimanyuAryan** [SciRuby/sciruby#48]
I am completely noob in SciRuby. For the first time I am using SciRuby. I am following this [video ](https://youtu.be/ZxjqsIluM88) to get an overview of how to use SciRuby and plot graphs, charts etc. When I go to localhost:8888 and I create new notebooks from right drop down(Ruby 2.2.3)

I am in home(~) dir 

![notebook](https://cloud.githubusercontent.com/assets/8083613/13724906/2ef179b8-e8ba-11e5-94b7-86a899d8b167.png)

Then at first it says Kernel connecting and then dead kernel message pops up again and again(within gap of few seconds). Nothing happens and the commands I am writing seems to have no effect. Please get this issue solved thanks a lot. 

![kernel](https://cloud.githubusercontent.com/assets/8083613/13724918/5edebb72-e8ba-11e5-90c7-421d35b93be4.png)

```

$ iruby notebook
Could not load bundler: Could not locate Gemfile or .bundle/ directory
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press Ctrl-C to quit now.
[I 01:13:51.976 NotebookApp] Serving notebooks from local directory: /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin
[I 01:13:51.976 NotebookApp] 0 active kernels 
[I 01:13:51.976 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 01:13:51.977 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Gtk-Message: Failed to load module "pantheon-filechooser-module"

(firefox:8219): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(firefox:8219): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(firefox:8219): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(firefox:8219): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(firefox:8219): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Gtk-Message: Failed to load module "canberra-gtk-module"
[I 01:14:32.931 NotebookApp] 302 GET / (127.0.0.1) 0.69ms
[I 01:14:39.766 NotebookApp] Creating new file in 
[I 01:14:53.999 NotebookApp] Creating new notebook in 
[I 01:14:56.223 NotebookApp] Kernel started: 463b14e0-9f3d-49c0-bd3d-6dd19e7b43d9
W, [2016-03-13T01:14:56.726775 #8272]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:163:in `rescue in root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:159:in `root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:71:in `bundle_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:401:in `configure_gem_home_and_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:57:in `configure'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:118:in `definition'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
You should install rbczmq or ffi_rzmq before running iruby notebook. See README.
F, [2016-03-13T01:14:56.821066 #8272] FATAL -- : Kernel died: uninitialized constant IRuby::Kernel::Session
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize': uninitialized constant IRuby::Kernel::Session (NameError)
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[I 01:14:59.223 NotebookApp] KernelRestarter: restarting kernel (1/5)
W, [2016-03-13T01:14:59.619447 #8309]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:163:in `rescue in root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:159:in `root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:71:in `bundle_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:401:in `configure_gem_home_and_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:57:in `configure'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:118:in `definition'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
You should install rbczmq or ffi_rzmq before running iruby notebook. See README.
F, [2016-03-13T01:14:59.696087 #8309] FATAL -- : Kernel died: uninitialized constant IRuby::Kernel::Session
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize': uninitialized constant IRuby::Kernel::Session (NameError)
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[I 01:15:02.231 NotebookApp] KernelRestarter: restarting kernel (2/5)
W, [2016-03-13T01:15:02.619460 #8312]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:163:in `rescue in root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:159:in `root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:71:in `bundle_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:401:in `configure_gem_home_and_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:57:in `configure'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:118:in `definition'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
You should install rbczmq or ffi_rzmq before running iruby notebook. See README.
F, [2016-03-13T01:15:02.703792 #8312] FATAL -- : Kernel died: uninitialized constant IRuby::Kernel::Session
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize': uninitialized constant IRuby::Kernel::Session (NameError)
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[I 01:15:05.239 NotebookApp] KernelRestarter: restarting kernel (3/5)
W, [2016-03-13T01:15:05.714227 #8316]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:163:in `rescue in root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:159:in `root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:71:in `bundle_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:401:in `configure_gem_home_and_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:57:in `configure'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:118:in `definition'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
You should install rbczmq or ffi_rzmq before running iruby notebook. See README.
F, [2016-03-13T01:15:05.788401 #8316] FATAL -- : Kernel died: uninitialized constant IRuby::Kernel::Session
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize': uninitialized constant IRuby::Kernel::Session (NameError)
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[W 01:15:06.731 NotebookApp] Timeout waiting for kernel_info reply from 463b14e0-9f3d-49c0-bd3d-6dd19e7b43d9
[I 01:15:08.247 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 463b14e0-9f3d-49c0-bd3d-6dd19e7b43d9 restarted
W, [2016-03-13T01:15:08.701757 #8318]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:163:in `rescue in root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:159:in `root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:71:in `bundle_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:401:in `configure_gem_home_and_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:57:in `configure'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:118:in `definition'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
You should install rbczmq or ffi_rzmq before running iruby notebook. See README.
F, [2016-03-13T01:15:08.779382 #8318] FATAL -- : Kernel died: uninitialized constant IRuby::Kernel::Session
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize': uninitialized constant IRuby::Kernel::Session (NameError)
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[W 01:15:11.256 NotebookApp] KernelRestarter: restart failed
[W 01:15:11.257 NotebookApp] Kernel 463b14e0-9f3d-49c0-bd3d-6dd19e7b43d9 died, removing from map.
ERROR:root:kernel 463b14e0-9f3d-49c0-bd3d-6dd19e7b43d9 restarted failed!
[W 01:15:11.329 NotebookApp] Kernel deleted before session
[W 01:15:11.330 NotebookApp] 410 DELETE /api/sessions/2709e672-f333-42d4-a84b-0c3ab68d3864 (127.0.0.1) 2.11ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=ruby
ryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:159:in `root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:71:in `bundle_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:401:in `configure_gem_home_and_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:57:in `configure'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:118:in `definition'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
You should install rbczmq or ffi_rzmq before running iruby notebook. See README.
F, [2016-03-13T01:15:02.703792 #8312] FATAL -- : Kernel died: uninitialized constant IRuby::Kernel::Session
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/kernel.rb:18:in `initialize': uninitialized constant IRuby::Kernel::Session (NameError)
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `new'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:70:in `run_kernel'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/bin/iruby:5:in `<top (required)>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `load'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/iruby:23:in `<main>'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[I 01:15:05.239 NotebookApp] KernelRestarter: restarting kernel (3/5)
W, [2016-03-13T01:15:05.714227 #8316]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:163:in `rescue in root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:159:in `root'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:71:in `bundle_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:401:in `configure_gem_home_and_path'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:57:in `configure'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:118:in `definition'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:109:in `check_bundler'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:67:in `run_kernel'
/home/abhimanyuaryan/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.8/lib/iruby/command.rb:34:in `run'
/home/abhimanyuarya[I 01:15:53.124 NotebookApp] Saving file at /Untitled.ipynb

```

**Comment by AbhimanyuAryan** [comment]
Fixed http://stackoverflow.com/questions/35999925/kernel-dies-when-creating-iruby-notebook
